"""empty message

Revision ID: f0c8d144e29a
Revises: e265ff267208
Create Date: 2022-03-04 20:30:46.241785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c8d144e29a'
down_revision = 'e265ff267208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('tweet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'tweet_id')
    # ### end Alembic commands ###
